project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!DS2_preview_work/"
  resources:
    - "Data/*.csv"

website:
  title: "MSCS 264: Data Science 2"
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - file: tech_setup.qmd
        text: "Tech Setup"
      - file: github_website.qmd
        text: "GitHub for DS2"
      - sidebar:activities
      - sidebar:projects

  sidebar:
    - id: activities
      title: "Activities"
      contents:
        - 01_review164.qmd
        - 02_maps_part1.qmd

    - id: projects
      title: "Projects"
      contents:
        - miniproject1.qmd

  page-footer:
    left: |
      &copy; Paul Roback, 2024<br>
      All content licensed under ![](https://static.thenounproject.com/png/70967-200.png){height=20px} ([CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/))
    right: |
      Site built with [Quarto](https://quarto.org/)

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    code-overflow: wrap

editor: source
